version: '3.8'
services:
   web:
       build: .
       command: python manage.py runserver localhost:8000
       ports:
           - 8000:8000
        depends_on: 
         - pgdb

      
   pgdb:
      image: postgres
      environment: 
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=123456
      container_name: pgdb